// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function() {
    var YoutrackProfile;
    YoutrackProfile = (function() {
      function YoutrackProfile(config) {
        this.config = config;
        this.addTimer = __bind(this.addTimer, this);
        this.addTimers = __bind(this.addTimers, this);
        this.projectNameSelector = "a[title^='Project: '], .sb-board-name";
        this.itemSelector = ".issueContainer, #editIssueDialog .sb-dlg-content";
        this.platformLoaded = false;
        this.interval = 250;
        this.loadHarvestPlatform();
        window.setInterval(this.addTimers, this.interval);
      }

      YoutrackProfile.prototype.loadHarvestPlatform = function() {
        var configScript, ph, platformConfig, platformScript,
          _this = this;
        platformConfig = {
          applicationName: "Youtrack",
          permalink: "http://%ACCOUNT_ID%.myjetbrains.com/youtrack/issue/%PROJECT_ID%-%ITEM_ID%",
          environment: this.config.environment
        };
        configScript = document.createElement("script");
        configScript.innerHTML = "window._harvestPlatformConfig = " + (JSON.stringify(platformConfig)) + ";";
        platformScript = document.createElement("script");
        platformScript.src = "//" + this.config.subdomain + this.config.domain + "/assets/platform.js";
        platformScript.async = true;
        ph = document.getElementsByTagName("script")[0];
        ph.parentNode.insertBefore(configScript, ph);
        ph.parentNode.insertBefore(platformScript, ph);
        return document.body.addEventListener("harvest-event:ready", function() {
          _this.platformLoaded = true;
          return _this.addTimers();
        });
      };

      YoutrackProfile.prototype.addTimers = function() {
        var item, items, _i, _len, _results;
        if (!this.platformLoaded) {
          return;
        }
        items = document.querySelectorAll(this.itemSelector);
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          if (!item.querySelector(".harvest-timer")) {
            _results.push(this.addTimer(item));
          }
        }
        return _results;
      };

      YoutrackProfile.prototype.addTimer = function(item) {
        var data;
        data = this.getDataForTimer(item);
        if (/*this.isTodoCompleted(item) ||*/ this.notEnoughInfo(data)) {
          return;
        }
        this.buildTimer(item, data);
        return this.notifyPlatformOfNewTimers();
      };

      YoutrackProfile.prototype.getDataForTimer = function(item) {
        var summary, itemName, link, linkParts, projectName, projectId, itemId, host, accountId;
        summary = item.querySelector(".issue-summary");
        if (summary) itemName = summary.innerText.trim();
        else {
          summary = item.querySelector("#ei_issuesummary input");
          if (summary) itemName = summary.value.trim();
        }
        issueId = item.querySelector(".issueId, .sb-issue-edit-id").innerText.trim();
        itemName = issueId + ": " + itemName;
        issueIdParts = issueId.split('-');
        projectId = issueIdParts[0];
        projectName = document.querySelector(this.projectNameSelector).firstChild.textContent.trim();
        itemId = issueIdParts[1];
        host = document.location.host.split('.');
        accountId = host[0];
        return {
          account: {
            id: accountId
          },
          project: {
            id: projectId,
            name: projectName
          },
          item: {
            id: itemId,
            name: itemName
          }
        };
      };

      YoutrackProfile.prototype.isTodoCompleted = function(item) {
        if (document.querySelector(".issueContainer.resolved")) { // Note, does not work for agile popups
          return true;
        } else {
          return false;
        }
      };

      YoutrackProfile.prototype.notEnoughInfo = function(data) {
        var _ref, _ref1;
        return !(((data != null ? (_ref = data.project) != null ? _ref.id : void 0 : void 0) != null) && ((data != null ? (_ref1 = data.item) != null ? _ref1.id : void 0 : void 0) != null));
      };

      YoutrackProfile.prototype.buildTimer = function(item, data) {
        var timer;
        timer = document.createElement("div");
        timer.className = "harvest-timer";
        timer.style.marginRight = "4px";
        timer.setAttribute("id", "harvest-youtrack-timer-" + data.item.id);
        timer.setAttribute("data-account", JSON.stringify(data.account));
        timer.setAttribute("data-project", JSON.stringify(data.project));
        timer.setAttribute("data-item", JSON.stringify(data.item));
        return item.insertBefore(timer, item.children[0]);
      };

      YoutrackProfile.prototype.notifyPlatformOfNewTimers = function() {
        var evt;
        evt = new CustomEvent("harvest-event:timers:chrome:add");
        return document.querySelector("#harvest-messaging").dispatchEvent(evt);
      };

      return YoutrackProfile;

    })();
    return chrome.runtime.sendMessage("retrieveConfig", function(config) {
      return new YoutrackProfile(config);
    });
  })();

}).call(this);
